### PR TITLE
Processed some lower RD outputs at MSU

### PR DESCRIPTION
**Pull request by clairekope**
Halo centers and velocities for 2392 RD0016 and RD0018; 2878 RD0016, RD0018, and RD0020 (new directory), and 5016 RD0016 and RD0018

### CODE REVIEW

**Comment by clairekope** [comment]
Hang on, there's some funny business. I may have copied things incorrectly.

**Comment by clairekope** [comment]
ok, everything is good now

**Comment by peeples** [comment]
I think these should be in order by redshift

**Comment by clairekope** [comment]
other parts of the files were not in order so I just tacked it on at the end, but I can throw them in where they should belong if needed

**Comment by peeples** [comment]
Making a note here to consider sorting by redshift later

**Pull request merged**
